# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      shell: |
            cd /src/Contacts/View
            dotnet add View.csproj package Newtonsoft.Json --version 13.0.3
            dotnet add View.csproj package CommunityToolkit.Mvvm --version 8.1.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build src/Contacts --no-restore
    - name: Test
      run: dotnet test src/Contacts --no-build --verbosity normal
